version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: weatherapp
    volumes:
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "15432:5432"

  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

networks:
  default:
    driver: bridge